import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import splitbee from '@splitbee/web';
splitbee.init()

export default function Home() {
  return (
    

    
    <div className={styles.container}>
      
        <div className={styles.back}>
            <Link href="/">
        <Image src="/back.svg" alt="RemoteUkraine" width={26} height={26} style="color:black"/> 
        </Link>
       </div>

      <Head>
        <title>RemoteUkraine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Link href="/">
      <Image src="/u.png" alt="RemoteUkraine" width={40} height={40} />
      </Link>
        <h1 className={styles.title}>
          Remote<a>Ukraine</a>
        </h1>

        <p className={styles.description}>
        You can contact us directly using the contacts below.  {' '}
          <br></br><br></br><code className={styles.code}>Contacts</code>
        </p>
        


       <div className={styles.contacts}>
       <a   href="mailto:info@remoteukraine.space"> <h4>info@remoteukraine.space</h4> </a>
          <a  href="https://twitter.com/ukraineremote"><h4>Twitter: remoteukrainespace</h4> </a> 
          <a href="https:/instagram.com/remoteukrainespace"><h4>Instagram: remoteukrainespace</h4> </a>
           
           <br></br>
          
       </div>

      
     
         



     
      </main>

      <footer className={styles.footer}>
        <a
         
          target="_blank"
          rel="noopener noreferrer"
        >
          {' '}
          
        </a>
      </footer>
    </div>
  )
}
