import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    

    
    <div className={styles.container}>
        <div className={styles.back}>
            <Link href="/">
        <Image src="/back.svg" alt="RemoteUkraine" width={26} height={26} style="color:black"/> 
        </Link>
       </div>

      <Head>
        <title>RemoteUkraine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Link href="/">
      <Image src="/u.png" alt="RemoteUkraine" width={40} height={40} />
      </Link>
        <h1 className={styles.title}>
          Remote<a>Ukraine</a>
        </h1>

        <p className={styles.description}>
       This information and Terms for Employers and Freelancers. Kiev timezone UTC/GMT +2  {' '}
          <br></br><br></br><code className={styles.code}>Our rules</code>
        </p>
        


       <div className={styles.list}>
           <h4>Only neutral tasks</h4>
           <h4>No politics</h4>
           <br></br>
          
       </div>

      
       <div className={styles.invB}>
        <Link href="/" passHref>
            <a className={styles.bbB}>
              <h2>Send request</h2>
              
            </a>
            </Link>
            </div>

            <div className={styles.invA}>
            <Link href="/contacts" passHref>
            <a className={styles.bbA}>
              <h2>Our contacts</h2>
            </a>
            </Link>
            </div>
         



     
      </main>

      <footer className={styles.footer}>
        <a
         
          target="_blank"
          rel="noopener noreferrer"
        >
          {' '}
          
        </a>
      </footer>
    </div>
  )
}
