import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import splitbee from '@splitbee/web';
splitbee.init()

export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>RemoteUkraine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Link href="/" passHref>
      <Image src="/u.png" alt="RemoteUkraine" width={40} height={40} />
      </Link>
        <h1 className={styles.title}>
          Remote<a>Ukraine</a>
        </h1>

        <p className={styles.description}>
        We are out of politics, we do not ask for gratuitous financial assistance, we are good at what we do and ready to work remotely {' '}
          <br></br><br></br><code className={styles.code}>We need your support</code>
        </p>
         <div className={styles.f400}>
        <Image src="/freel.svg" alt="RemoteUkraine" width={158} height={60}/>
        </div>


       
        <div className={styles.inv3}>
        <Link href="/skills" passHref>
            <a className={styles.bb3}>
              <h2>Our Community</h2>
            </a>
            </Link>
            </div>

           

        <div className={styles.inv}>
        <Link href="/employer" passHref>
            <a className={styles.bb}>
              <h2>I am an Employer</h2>
              
            </a>
            </Link>
            </div>

            <div className={styles.inv2}>
            <a href="https://sx9jnlfxlbh.typeform.com/to/UWKyNet7" className={styles.bb2}>
              <h2>Вказати резюме</h2>
            </a>
            </div>
    




      

         



     
      </main>

      <footer className={styles.footer}>
        <a
         
          target="_blank"
          rel="noopener noreferrer"
        >
          2022{' '}
          
        </a>
      </footer>
    </div>
  )
}
